Repository devofnest/jobAssist, pull requests merged in 2025-03, with the labels that each got.

#4 backend 수정
  backend/README.md
Labels: documentation

#5 [update] front
  front/README.md
Labels: documentation

#6 [feat] front 초기설정 React.js + Vite 업로드
  front/.gitignore
  front/README.md
  front/eslint.config.js
  front/index.html
  front/package.json
  front/public/vite.svg
  front/src/App.css
  front/src/App.jsx
  front/src/assets/react.svg
  front/src/index.css
  front/src/main.jsx
  front/vite.config.js
  front/yarn.lock
Labels: enhancement

#7 [update] front search section
  front/src/App.css
  front/src/App.jsx
  front/src/data/dummy_data.json
  front/src/index.css
  front/src/main.jsx
Labels: duplicate
